CREATE TABLE ND_ROLES (
  ID BIGINT NOT NULL,
  NAME VARCHAR (255) NOT NULL,
  canCreateNewArticle BOOLEAN NOT NULL,
  canModifyOwnArticle BOOLEAN NOT NULL,
  canDeleteArticle BOOLEAN NOT NULL,
  canModifyArticle BOOLEAN NOT NULL,
  canAddUser BOOLEAN NOT NULL,
  canDeleteUser BOOLEAN NOT NULL,
  canModifyUser BOOLEAN NOT NULL,
  canCreateRole BOOLEAN NOT NULL,
  canDeleteRole BOOLEAN NOT NULL,
  canModifyRole BOOLEAN NOT NULL,
  CONSTRAINT USER_ROLE_PK PRIMARY KEY (ID),
  CONSTRAINT USER_ROLE_UN UNIQUE (NAME)
);
CREATE SEQUENCE ND_ROLES_ID_SEQ OWNED BY ND_ROLES.ID;

CREATE TABLE ND_USERS_ROLES (
  USER_ID BIGINT NOT NULL,
  ROLE_ID BIGINT NOT NULL,
  CONSTRAINT USERS_ROLES_PK PRIMARY KEY (USER_ID,ROLE_ID),
  CONSTRAINT USERS_FK FOREIGN KEY (USER_ID)
  REFERENCES ND_USERS (ID),
  CONSTRAINT ROLES_FK FOREIGN KEY (ROLE_ID)
  REFERENCES ND_ROLES (ID)
);