CREATE TABLE ND_ROLES (
  ID BIGINT NOT NULL,
  NAME VARCHAR (255) NOT NULL,
  CAN_CREATE_NEW_ARTICLE BOOLEAN NOT NULL,
  CAN_MODIFY_OWN_ARTICLE BOOLEAN NOT NULL,
  CAN_DELETE_ARTICLE BOOLEAN NOT NULL,
  CAN_MODIFY_ARTICLE BOOLEAN NOT NULL,
  CAN_ADD_USER BOOLEAN NOT NULL,
  CAN_DELETE_USER BOOLEAN NOT NULL,
  CAN_MODIFY_USER BOOLEAN NOT NULL,
  CAN_CREATE_ROLE BOOLEAN NOT NULL,
  CAN_DELETE_ROLE BOOLEAN NOT NULL,
  CAN_MODIFY_ROLE BOOLEAN NOT NULL,
  CONSTRAINT USER_ROLE_PK PRIMARY KEY (ID),
  CONSTRAINT USER_ROLE_UN UNIQUE (NAME)
);
CREATE SEQUENCE ND_ROLES_ID_SEQ;

CREATE TABLE ND_USERS_ROLES (
  USER_ID BIGINT NOT NULL,
  ROLE_ID BIGINT NOT NULL,
  CONSTRAINT USERS_ROLES_PK PRIMARY KEY (USER_ID,ROLE_ID),
  CONSTRAINT USERS_FK FOREIGN KEY (USER_ID)
  REFERENCES ND_USERS (ID),
  CONSTRAINT ROLES_FK FOREIGN KEY (ROLE_ID)
  REFERENCES ND_ROLES (ID)
);