# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: newsdemo
      POSTGRES_USER: newsdemo
      POSTGRES_PASSWORD: newsdemo
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "5488:8080"
