CREATE TABLE ND_USERS (
  ID BIGINT NOT NULL,
  USERNAME VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  CONSTRAINT ND_USERS_PK PRIMARY KEY (ID),
  CONSTRAINT ND_USERS_USERNAME_UN UNIQUE (USERNAME)
);

CREATE SEQUENCE ND_USERS_ID_SEQ OWNED BY ND_USERS.ID;

CREATE TABLE ND_USERS_ROLES (
ID BIGINT NOT NULL,
  NAME VARCHAR (255) NOT NULL,
  CONSTRAINT USER_ROLE_PK PRIMARY KEY (ID),
  CONSTRAINT USER_ROLE_UN UNIQUE (NAME)
);
CREATE SEQUENCE ND_USERS_ROLES_ID_SEQ OWNED BY ND_USERS_ROLES.ID;

CREATE TABLE USERS_ROLES (
USER_ID BIGINT NOT NULL,
ROLE_ID BIGINT NOT NULL,
CONSTRAINT USERS_ROLES_UN UNIQUE (USER_ID,ROLE_ID),
CONSTRAINT USERS_FK FOREIGN KEY (USER_ID)
REFERENCES ND_USERS (ID),
CONSTRAINT ROLES_FK FOREIGN KEY (ROLE_ID)
REFERENCES ND_USERS_ROLES (ID)
);


INSERT INTO ND_USERS (ID, USERNAME, PASSWORD)
 VALUES (123456789,'newsdemo123','newsdemo123');
 
 INSERT INTO ND_USERS_ROLES (ID, NAME)
 VALUES (1,'ROLE_USER');
 
 INSERT INTO USERS_ROLES (USER_ID,ROLE_ID) 
 VALUES (123456789,1);
