CREATE TABLE ND_ARTICLE (
  ID BIGINT NOT NULL,
  TITLE VARCHAR(255) NOT NULL,
  CONTENT VARCHAR(255) NOT NULL,
  POSTING_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
  CONSTRAINT ND_ARTICLE_PK PRIMARY KEY (ID),
  CONSTRAINT ND_ARTICLE_TITLE_UN UNIQUE (TITLE)
 
);

CREATE SEQUENCE ND_ARTICLE_ID_SEQ OWNED BY ND_ARTICLE.ID;

CREATE TABLE ND_USERS_ARTICLE (
  USER_ID BIGINT NOT NULL,
  ARTICLE_ID BIGINT NOT NULL,
  CONSTRAINT USERS_ARTICLE_PK PRIMARY KEY (USER_ID,ARTICLE_ID),
  CONSTRAINT USERS_FK FOREIGN KEY (USER_ID)
  REFERENCES ND_USERS (ID),
  CONSTRAINT ARTICLE_FK FOREIGN KEY (ARTICLE_ID)
  REFERENCES ND_ARTICLE (ID)
);
