CREATE TABLE ND_ARTICLE (
  ID BIGINT NOT NULL,
  TITLE VARCHAR(255) NOT NULL,
  CONTENT VARCHAR(255) NOT NULL,
  POSTING_DATE TIMESTAMP NOT NULL,
  AUTHOR_ID BIGINT NOT NULL,
  CONSTRAINT ND_ARTICLE_PK PRIMARY KEY (ID),
  CONSTRAINT ARTICLE_FK FOREIGN KEY (AUTHOR_ID)
  REFERENCES ND_USERS (ID)
 
);

CREATE SEQUENCE ND_ARTICLE_ID_SEQ OWNED BY ND_ARTICLE.ID;

